export const GET_QUESTIONS = 'GET_QUESTIONS';
export const POSITION_ANSWER = 'POSITION_ANSWER';
export const SET_ACTIVE_ANSWER = 'SET_ACTIVE_ANSWER';
export const SET_ACTIVE_QUESTION = 'SET_ACTIVE_QUESTION';
export const GET_QUESTIONS_START = 'GET_QUESTIONS_START';
export const GET_QUESTIONS_ERRORED = 'GET_QUESTIONS_ERRORED';
export const GET_QUESTIONS_FULFILLED = 'GET_QUESTIONS_FULFILLED';
export const GET_QUESTIONS_REQUESTED = 'GET_QUESTIONS_REQUESTED';
